### ISSUE TITLE
Only absolute URLs are supported

### ISSUE THREAD

**Issue by aryeharmon** [abdhass/telegram-channel-scraper#12]
getting the follwoing error while running index.js
```
(node:7395) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/mnt/sdc/Code/telegram-channel-scraper/node_modules/node-fetch/lib/index.js:1257:9)
    at /mnt/sdc/Code/telegram-channel-scraper/node_modules/node-fetch/lib/index.js:1322:19
    at new Promise (<anonymous>)
    at fetch (/mnt/sdc/Code/telegram-channel-scraper/node_modules/node-fetch/lib/index.js:1319:9)
    at sendToServer (/mnt/sdc/Code/telegram-channel-scraper/chat-history.js:77:26)
    at chatHistory (/mnt/sdc/Code/telegram-channel-scraper/chat-history.js:56:24)
    at async run (/mnt/sdc/Code/telegram-channel-scraper/index.js:7:3)
(node:7395) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7395) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by cyvitor** [comment]
i've got the same issue
