### ISSUE TITLE
ENOENT: no such file or directory, open 'storage/chat.json'

### ISSUE THREAD

**Issue by martyns0n** [abdhass/telegram-channel-scraper#2]
Hi, on Ubuntu and WSL i have a problem with scraper initialization. There is no problems on Mac.
How i can fix this?

```bash
> node index.js 

{ Error: ENOENT: no such file or directory, open 'storage/chat.json'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'storage/chat.json' }
already signed in
[0.302] req_pq error read ECONNRESET
Get networker error { Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: { 'User-Agent': 'axios/0.16.2', 'Content-Length': 40 },
     method: 'post',
     responseType: 'arraybuffer',
     url: 'http://149.154.167.51/apiw1',
     data: ArrayBuffer { byteLength: 40 } },
  request: 
   Writable {
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events: 
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options: 
      { protocol: 'http:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        hostname: '149.154.167.51',
        port: null,
        path: '/apiw1',
        method: 'post',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        nativeProtocols: [Object],
        pathname: '/apiw1' },
     _redirectCount: 0,
     _redirects: [],
     _requestBodyLength: 40,
     _requestBodyBuffers: [ [Object] ],
     _onNativeResponse: [Function],
     _currentRequest: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /apiw1 HTTP/1.1\r\nUser-Agent: axios/0.16.2\r\nContent-Length: 40\r\nHost: 149.154.167.51\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/apiw1',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'http://149.154.167.51/apiw1' },
  response: undefined } Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
(node:5735) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
(node:5735) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5735) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Unhandled rejection Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)

Unhandled rejection Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
```

**Comment by martyns0n** [comment]
Fixed by creating chat.json with {} content, but after getting error from [this issue](https://github.com/abdhass/telegram-channel-scraper/issues/1)

**Comment by abdhass** [comment]
I was just going to ask you to create a empty chat.json file. Glad you got it working.

**Comment by HansHauge** [comment]
The same thing applies to `db.json`
