### ISSUE TITLE
Only HTTP(S) protocols are supported

### ISSUE THREAD

**Issue by TripleThreads** [abdhass/telegram-channel-scraper#6]
(node:3237) UnhandledPromiseRejectionWarning: TypeError: Only HTTP(S) protocols are supported
    at getNodeRequestOptions (/home/segni/Documents/telegram-channel-scraper/node_modules/node-fetch/lib/index.js:1261:9)
    at /home/segni/Documents/telegram-channel-scraper/node_modules/node-fetch/lib/index.js:1322:19
    at new Promise (<anonymous>)
    at fetch (/home/segni/Documents/telegram-channel-scraper/node_modules/node-fetch/lib/index.js:1319:9)
    at sendToServer (/home/segni/Documents/telegram-channel-scraper/chat-history.js:69:26)
    at chatHistory (/home/segni/Documents/telegram-channel-scraper/chat-history.js:56:24)
(node:3237) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3237) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SneakBug8** [comment]
Still doesn't work by september 2020

**Comment by abdhass** [comment]
Unfortunately not. But hey I will work on this if people are interested

**Comment by ItsNash0** [comment]
you just need to  run npm upgrade
it seems it just requires a node-fetch upgrade 👍

**Comment by HoJinKind** [comment]
> you just need to run npm upgrade
> it seems it just requires a node-fetch upgrade 👍

This still doesnt work for me? i tried running 
npm install node-fetch@latest
